### ISSUE TITLE
Playground fails to build on Node 13

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen#1]
See https://github.com/sdkgen/sdkgen/runs/433452998?check_suite_focus=true for details.

Some dependency is installing `sharp` and it seems to not support Node 13 yet? Upgrading to latest version should solve the problem: https://github.com/lovell/sharp/issues/1909

**Comment by kevinoliveira** [comment]
@lbguilherme the pull request above is now merged, the issue is resolved.
