### ISSUE TITLE
Unable to run unit test in Flutter

### ISSUE THREAD

**Issue by isorensen** [sdkgen/sdkgen#11]
When running a unit test in Flutter, the exception below is thrown:

MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

![image](https://user-images.githubusercontent.com/3399976/74195808-cf6c0b00-4c3a-11ea-9a82-e168e10e2539.png)

**Comment by lbguilherme** [comment]
@isorensen The fix for this issue has been released: https://github.com/sdkgen/sdkgen/releases/tag/1.0.65
