### ISSUE TITLE
Use @dataclass on Flutter objects

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen#114]
Currently Flutter objects are generated as simple classes with fields and a constructor. We could change them to be annotated with [`@dataClass`](https://pub.dev/packages/dataclass). This means every object will have a proper `==` operator, a better `toString()` and correct `hashCode` for using in containers an so on. The breaking change is that all fields are required to be marked as `final`, meaning they can only be set in the constructor.

What do you think about the pros and cons of this change? Mutable simple objects -> Immutable dataclass objects.

---

```
type TestStruct {
  hello: string
  stuff: int?
}
```

Currently generates this:

```
class TestStruct {
  String hello;
  int stuff;

  TestStruct({@required this.hello, this.stuff});
}
```

But could generate this:

```
@dataClass
class TestStruct {
  final String hello;
  final int stuff;

  TestStruct({@required this.hello, this.stuff});
}
```

**Comment by danilocubos** [comment]
I don't see any problems with the variables being immutable, as they should be used only for API communication.
