### ISSUE TITLE
Replace Buffer with ArrayBuffer for browser target

### ISSUE THREAD

**Issue by vhfmag** [sdkgen/sdkgen#176]
Currently, sdkgen's `bytes` is converted to `Buffer` in the browser target. I'd argue that's suboptimal since:

- `Buffer` is a Node.js type, not a native Javascript type
- Webpack used to polyfill `Buffer` by default but, from `@5` on, this is opt-in ([reference](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure))
- There is a raw bytes primitive native no Javascript, `ArrayBuffer`, that's been around long enough to be available all the way to IE10 ([reference](https://caniuse.com/mdn-javascript_builtins_arraybuffer))

Based on the above points, I suggest we remove `Buffer` from browser code and stick with `ArrayBuffer`. If that's agreed upon, I'd be happy to work on it, but I might need someone to point me what files, other than `typescript-generator/src/helpers.ts`, I might need to change.

**Comment by lbguilherme** [comment]
Agreed. Since this is a breaking change, I'm scheduling it for the 2.0.0 release.
