### ISSUE TITLE
Enum as means of Tagged Unions

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen#249]
We currently have an implementation of Untagged Unions at PR #194 (currently in review). But I came across another syntax for it that might be simpler to implement and keep code cleaner: Using enums.

```
type Shape enum {
	point
	square(side: float)
	rectangle(width: float, height: float)
	circle(radius: float)
	polygon(points: {
		x: float
		y: float
	}[])
}
```

It could also allow recursive types:

```
type Tree enum {
	leaf(data: string)
	node(data: string, left: Tree?, right: Tree?)
}
```

Here is an example from #194:

```
fn sendValue(value: string | int)

type TextMessage {
	text: string
}

type ImageMessage {
	imageUrl: url
	legend: string
}

type Message {
	destination: string
	body: TextMessage | ImageMessage
}

fn getMessages(): Message
```

And this example with this new syntax:

```
type ValueToSend enum {
	string(value: string)
	int(value: int)
}

fn sendValue(value: ValueToSend)

type Message {
	destination: string
	body: enum {
	  image(url: url, legend: string)
	  text(text: string)
	}
}

fn getMessages(): Message
```

This implementation is better overall and does not introduce any breaking change to the syntax. Existing enums would be still valid.

Should we drop #194 and go for this syntax?

**Comment by joshuapassos** [comment]
I prefer to use this approach in union types. 
In Sdkgen uses, it makes more sense to use types using tags. These facilitating flow implementations in web applications
