### ISSUE TITLE
Error in client.dart generation for optional arrays

### ISSUE THREAD

**Issue by isorensen** [sdkgen/sdkgen#78]
# Summary

When declaring a type in sdkgen as optional array of strings, for example, the client.dart is declared incorrectly, without "mapping" it toList()

## Steps to Reproduce

In types.sdkgen, change a string[] to string[]?, and check client.dart generation.  

```diff
diff --git a/src/shared/types.sdkgen b/src/shared/types.sdkgen
index f5eda71..5c5df56 100644
--- a/src/shared/types.sdkgen
+++ b/src/shared/types.sdkgen
@@ -22,7 +22,7 @@ type Clause {
     number: int?
     title: string?
     intro: string?
-    paragraphs: string[]
+    paragraphs: string[]?
 }
```

## Expected results

```dart
..paragraphs = (fields["paragraphs"] as List).map((e) => e as String).toList()
```

## Actual results

```dart
..paragraphs = fields["paragraphs"] as List<String>
```

And when calling a method that uses this in Flutter, it returns an error:  
![image](https://user-images.githubusercontent.com/3399976/80708645-6752f580-8ac2-11ea-825c-ab6285394e21.png)

**Comment by isorensen** [comment]
@lbguilherme , alguma previsão de quando atacarão esta issue?  
Jatobá adicionou outra list no backend, sem se atentar a isto, e causou erro. Como já conhecemos, já identificamos, mas seria bom não nos preocuparmos com isto:  
<img width="648" alt="image" src="https://user-images.githubusercontent.com/3399976/81685046-1205d500-942e-11ea-85b2-60e919bf1f22.png">
Abs e obrigado

**Comment by isorensen** [comment]
Valeu @lbguilherme e @dgadelha . Enquanto eu estava tentando fazer um "workaround", vi que, mesmo vindo o ".map" corretamente, é importante tratar se for "nulo", pois se vier nulo, o .map do Flutter vai cuspir erro. Isto já está tratado no que vocês fizeram aqui? Avaliem se precisará reabrir a issue. Não sei se consegui explicar bem, mas vejam o código aí. Se ainda não entenderam, me avisem:  

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/3399976/81706502-7339a280-9446-11ea-8440-f56f9e2f0b83.png">  

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/3399976/81706864-a419d780-9446-11ea-8e82-490a6b98fc16.png">

**Comment by dgadelha** [comment]
Foi tratado sim, aqui:
https://github.com/sdkgen/sdkgen/pull/80/files#diff-7bd3d0b95bb0ac2f3f1185bea706cf23R67

**Comment by isorensen** [comment]
@dgadelha , alguma previsão de quando sai a próxima release com este fix?

**Comment by dgadelha** [comment]
Vocês podem usar a versão com a tag `dev` do sdkgen CLI para gerar o client com o fix:

```
npm i -g @sdkgen/cli@dev
sdkgen src/api.sdkgen -o client.dart -t flutter
```
