### ISSUE TITLE
[BUG] skdgen breaking latest version.  Cannot use import statement outside a module

### ISSUE THREAD

**Issue by iwaduarte** [sdkgen/sdkgen#810]
SyntaxError: Cannot use import statement outside a module

![image](https://github.com/sdkgen/sdkgen/assets/24816534/655af814-ea9a-4510-bf3c-6288688277de)

I think the culprit for the breaking is this PR:
https://github.com/sdkgen/sdkgen/pull/779

There is an attempt to convert CJS to ESM but a few configurations are missing:

1 - package.json must have the type: "module" property set.
2 - All files resolutions should have the extension (.js) therefore:

![image](https://github.com/sdkgen/sdkgen/assets/24816534/085574e7-daa2-4ea4-9cf7-a254e07babb1)

Would not work.

I do not know if 0.0.0@DEV should be published to npm ( maybe CI/CD should be fixed too?)

**Comment by dgadelha** [comment]
Corrigido via https://github.com/sdkgen/sdkgen/commit/20945d8bd6da5dc80463c6ed7f652805d60ca75a
