### ISSUE TITLE
Type cast error

### ISSUE THREAD

**Issue by daniloapr** [sdkgen/sdkgen#91]
API call successfully completed, but on mobile is thrown a SdkgenError with the following message: 

type int is not a substype of type double in type cast.

**Comment by dgadelha** [comment]
Are you using the latest versions for both generated files and runtime?

**Comment by daniloapr** [comment]
I am using:

On API:
"@sdkgen/node-runtime": "^1.0.65",
"@sdkgen/cli": "^1.0.65",

On Dart:
sdkgen_runtime: ^1.2.2

With the last client.dart file.

**Comment by lbguilherme** [comment]
This isn't the issue, but you shouldn't use a newer client with an older API. The other way is fine. Please update the API to 1.2.2.

About the error, do you have a stack trace and the request that caused it?

**Comment by daniloapr** [comment]
I updated the API to 1.2.2, generated a new `client.dart` file and the problem was solved!
